### ISSUE TITLE
Conformity?

### ISSUE THREAD

**Issue by ChristophGmeiner** [Priesemann-Group/covid19_npis_europe#2]
First of all: Great work. As a Data scientist and coder I really habe to say: Kudos und Great Great work. But as a social scientist I have to say: The assumption of 100% conformity (i.e. All People stick to all rules) especially in times like these are very unrealistic. Do you plan to integrate nonconform behaviour in your models?

**Comment by jdehning** [comment]
Hi there, first of all, thanks for your interest. You may have noticed that this repository is very much a work in progress and one can always expect changes and additions to our model.

I will try to answer your question or give you a bit of insight in the following:
We do not model "100% conformity" but the total effectivity of non-pharmaceutical interventions(NPI). If you take a look at our documentation [here](https://covid19-npis-europe.readthedocs.io/en/latest/doc/model.html#covid19_npis.model.reproduction_number.construct_R_t) you can see that this total effectivity is modelled in a hierarchical manner i.e. it is depending on a global contribution (for the specific NPI), an country-specific contribution and an age group-specific contribution. If there is less conformity in a country/region and an age group we assume that we will see these differences to translate into effectivity. Other than that, if an intervention is not accepted in every country/age group (less conformity) the total effectiveness of the intervention will be low. 

Nonetheless we do not model a time dependence for this effectivity yet, i.e. people behaviour may conform less to restrictions over time. Maybe we will add this at some point but there are other more important parts which we have to get working first.
